name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name:  Build and Push Images
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DOCKERHUB_USERNAME: ${{ secrets.ORG_DOCKER_HUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.ORG_DOCKER_HUB_TOKEN }}
      RELEASE_VERSION: ~
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        run: |
          docker run --rm -v "${PWD}":/app michcald/semantic-release
          if test -f .RELEASE_VERSION; then
            release_version="$(cat .RELEASE_VERSION)"
            echo "::set-env name=RELEASE_VERSION::$release_version"
          fi
      - name: Dockerhub login
        if: env.RELEASE_VERSION != ''
        run: docker login --username=${DOCKERHUB_USERNAME} --password=${DOCKERHUB_PASSWORD}
      - name: Build and Push
        if: env.RELEASE_VERSION != ''
        run: make
      - name: Dockerhub logout
        if: env.RELEASE_VERSION != ''
        run: docker logout
